#ifndef ACCMUT_CONFIG_H
#define ACCMUT_CONFIG_H

//SWITCH FOR IR-LEVEL MUTATION GENERATION
#define ACCMUT_GEN_MUT 1

//SWITCH FOR STATIC ANALYSIS
#define ACCMUT_STATIC_ANALYSIS_FILTER 0
#define ACCMUT_STATIC_ANALYSIS_INSTRUEMENT_FORK 0

//SWITCH FOR DYNAMIC ANALYSIS
#define ACCMUT_DYNAMIC_ANALYSIS_INSTRUEMENT 0

#endif
