##===- clang/lib/CodeGen/Makefile --------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
#
# This implements the AST -> LLVM code generation library for the 
# C-Language front-end.
#
##===----------------------------------------------------------------------===##

CLANG_LEVEL := ../..
LIBRARYNAME := clangCodeGen

#LLVMLIBS = libAccMut.a
#USEDLIBS = $(LLVM_OBJ_ROOT)/$(BuildMode)/lib/libAccMut.a
#libAccMut.a
#LINK_COMPONENTS = accmut

include $(CLANG_LEVEL)/Makefile

